### ISSUE TITLE
Black background while loading with Glide and Picasso

### ISSUE THREAD

**Issue by mcassiano** [subinkrishna/CircularImageView#4]
Apparently the outer view is getting a black background when loading the image with either one of these image loading libraries.

``` java
Picasso.with(context)
                .load(url)
                .fit()
                .into(imageView);
```

or

``` java
Picasso.with(context)
                .load(url)
                .placeholder(placeholder)
                .fit()
                .into(imageView);
```

<img width="172" alt="screen shot 2016-10-19 at 12 09 39" src="https://cloud.githubusercontent.com/assets/1852609/19522156/f5d1f2f0-95f4-11e6-9e80-ba5a77b3608b.png">
<img width="283" alt="screen shot 2016-10-19 at 12 09 45" src="https://cloud.githubusercontent.com/assets/1852609/19522157/f5d558e6-95f4-11e6-9598-95c5ee90a062.png">

**Comment by subinkrishna** [comment]
Thank you for the feedback. Please let me know the version of Picasso/Glide you are using. Also, I would like to know if you are using any background color for the ImageView.

**Comment by mcassiano** [comment]
Sorry, forgot to mention that!

Picasso 2.5.2
Glide 3.7.0

Also, very nice work! :D

Not using any background and this glitch doesn't happen all the time, first time it is shown on the screen, it looks ok.

**Comment by subinkrishna** [comment]
Thank you. I use the following code in the sample app and seems to work all the time:

```
Picasso.with(this).load("https://raw.githubusercontent.com/subinkrishna/CircularImageView/master/art/cat_original.jpg")
        .noFade()
        .placeholder(R.drawable.placeholder)
        .resize(width, height)
        .centerCrop()
        .into(mImage);
```

Anyways, I will look in to the issue.

**Comment by mcassiano** [comment]
I thought that this might be the problem since animation is problematic with other libs too, but noFade() (which seems to be Picasso's for Glide's .dontAnimate()) did not did the trick. Odd.

**Comment by subinkrishna** [comment]
Unfortunately I am not able to reproduce this yet. Is this a device/OS version specific issue?

**Comment by mcassiano** [comment]
Hi. Sorry for the delay. Havent checked this, i'll look into to it when I have time!

**Comment by AmitPrajapati1902** [comment]
Please try this  

`android:background="@color/white"`
