### ISSUE TITLE
Loading Vector

### ISSUE THREAD

**Issue by falmanna** [subinkrishna/CircularImageView#5]
Hello,

I am trying to load a vector drawable into my view, but it is showing full black color.
I tried to load it from xml and from java code, both giving me black image.

![capture](https://cloud.githubusercontent.com/assets/3227740/21226010/a9c2921c-c2e4-11e6-8df4-79e07bea3a09.PNG)

**Comment by subinkrishna** [comment]
Thank you for your feedback. Please try this:

```java
final Bitmap bitmap = getBitmap(context, resId, width, height);
image.setImageBitmap(bitmap);

// Converts the drawable resource to Bitmap
public static Bitmap getBitmap(Context context,
                               int resId,
                               int w,
                               int h) {
    Drawable drawable = AppCompatDrawableManager.get().getDrawable(context, resId);
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
        drawable = (DrawableCompat.wrap(drawable)).mutate();
    }

    Bitmap bitmap = (w > 0) && (h > 0) 
            ? Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
            : null;
    if (null != bitmap) {
        final Canvas canvas = new Canvas(bitmap);
        drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
        drawable.draw(canvas);
    }

    return bitmap;
}
```

Please let me know if it works.

**Comment by falmanna** [comment]
Thank you for following up.
Now it is a different problem, see the screenshot.  


![screenshot_20161217-035136](https://cloud.githubusercontent.com/assets/3227740/21283022/b3d38896-c40c-11e6-8ede-e1f381d1759f.png)

**Comment by subinkrishna** [comment]
Its very hard to understand the problem from this screenshot. Please share more information.

**Comment by falmanna** [comment]
Sorry about that. 
At the beginning, it was showing black instead of the vector image. Now after using your code snippet, it is showing the border color instead of the vector image. 
I then used a normal imageview view for my image and or worked without a problem.

**Comment by subinkrishna** [comment]
Can you share some code snippets?

**Comment by falmanna** [comment]
```
Bitmap bitmap = getBitmap(mContext, UiUtils.getCategoryIcon(mItemList.get(position).categoryId), 80, 80);
holder.categoryPhoto.setImageBitmap(bitmap);
holder.categoryPhoto.setBorderColor(ContextCompat.getColor(mContext, UiUtils.getColor(mItemList.get(position).categoryId)));
```

This is the code I am using inside my adapter to set color and image for each item.  
`UiUtils.getCategoryIcon(mItemList.get(position).categoryId)` this method is just a util to map ids to image resources. `ContextCompat.getColor(mContext, UiUtils.getColor(mItemList.get(position).categoryId))` and this one is for mapping color.

note that the same code is working well with `png icon`, but not with `vector icon`

**Comment by subinkrishna** [comment]
Can you send a sample vector asset also, if possible?

**Comment by falmanna** [comment]
I cant upload it here on github, so download it from this link
https://mega.nz/#!oElESJKQ!SaolnZC53DB9v_I36oX1yVor8bmvvygpaIzKlSkvTug

**Comment by subinkrishna** [comment]
Looks like it works for me!
<img width="159" alt="screen shot 2016-12-20 at 1 36 15 pm" src="https://cloud.githubusercontent.com/assets/360711/21366973/6a48af1c-c6b9-11e6-940b-e5562afcd7c5.png">

I used the following code:
```java
mImage.setImageBitmap(getBitmap(this, R.drawable.ic_sport, 
    80, // width of ImageView 
    80  // height of ImageView 
));
```

**Comment by falmanna** [comment]
Did you try to set border color?
Also even if it works with border color, the image shouldn't be cropped like this.

here is how I did it with an Imageview inside rounded cardview

![screenshot_20161220-235045](https://cloud.githubusercontent.com/assets/3227740/21367638/f21f852c-c70f-11e6-9bc8-3f63bde2bcb9.png)

**Comment by subinkrishna** [comment]
Yes, I applied a white border to the SVG.

Current implementation of `CircularImageView` fits the image to ImageView size before clipping it to a circle. This is intentional. This is to avoid the background color bleeding through the edges. One way to fix it is to use an XML drawable like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <item android:drawable="@android:color/darker_gray"/>
    <item>
        <bitmap
            android:src="@drawable/ic_tune_black_24dp"
            android:gravity="center"/>
    </item>
</layer-list>
```
